name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:
    inputs:
      vm_host:
        description: 'VM IP address or hostname'
        required: true
        type: string
      tag:
        description: 'Docker image tag'
        required: false
        type: string
        default: 'latest'

jobs:
  build:
    uses: ./.github/workflows/frontend-build-push.yml
    with:
      tag: ${{ github.event.inputs.tag || 'latest' }}
    secrets: inherit

  deploy:
    needs: [build]
    if: ${{ needs.build.result == 'success' }}
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      vm_host: ${{ github.event.inputs.vm_host || secrets.VM_HOST }}
      image_tag: ${{ github.event.inputs.tag || 'latest' }}
    secrets: inherit