name: Build and Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:
    inputs:
      vm_host:
        description: 'VM IP address or hostname'
        required: false
        type: string
        default: ''
      tag:
        description: 'Docker image tag'
        required: false
        type: string
        default: 'latest'

env:
  VM_HOST: ${{ github.event.inputs.vm_host || secrets.VM_HOST }}
  IMAGE_TAG: ${{ inputs.tag || 'latest' }}

jobs:
  build:
    uses: ./.github/workflows/backend-build-push.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit

  deploy:
    needs: [build]
    if: ${{ needs.build.result == 'success' }}
    uses: ./.github/workflows/deploy-backend.yml
    with:
      vm_host: ${{ env.VM_HOST }}
      image_tag: ${{ env.IMAGE_TAG }}
    secrets: inherit