name: Build and Push Frontend Image

on:
  workflow_call:
    inputs:
      tag:
        description: "Custom tag for the image"
        required: false
        type: string
        default: "latest"
    outputs:
      image-tag:
        description: "The built image tag"
        value: ${{ jobs.build-and-push-frontend.outputs.image-tag }}
  workflow_dispatch:
    inputs:
      tag:
        description: "Custom tag for the image"
        required: false
        type: string
        default: "latest"

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-frontend

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ github.event.inputs.tag || inputs.tag || 'latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag || inputs.tag || 'latest' }}